/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    enquiries: Enquiry;
    services: Service;
    locations: Location;
    reviews: Review;
    faqs: Faq;
    pages: Page;
    media: Media;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    enquiries: EnquiriesSelect<false> | EnquiriesSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    locations: LocationsSelect<false> | LocationsSelect<true>;
    reviews: ReviewsSelect<false> | ReviewsSelect<true>;
    faqs: FaqsSelect<false> | FaqsSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'home-page': HomePage;
    'page-copy': PageCopy;
    'combo-template': ComboTemplate;
    'site-settings': SiteSetting;
    navigation: Navigation;
  };
  globalsSelect: {
    'home-page': HomePageSelect<false> | HomePageSelect<true>;
    'page-copy': PageCopySelect<false> | PageCopySelect<true>;
    'combo-template': ComboTemplateSelect<false> | ComboTemplateSelect<true>;
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    navigation: NavigationSelect<false> | NavigationSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Service orders and quote requests from the website.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "enquiries".
 */
export interface Enquiry {
  id: number;
  type: 'order' | 'quote' | 'contact';
  status: 'new' | 'contacted' | 'booked' | 'closed';
  name: string;
  phone: string;
  email?: string | null;
  serviceLabel?: string | null;
  cityLabel?: string | null;
  /**
   * When they need it.
   */
  when?: string | null;
  message?: string | null;
  /**
   * The page the form was submitted from.
   */
  sourcePage?: string | null;
  /**
   * Internal notes. Not shown to the customer.
   */
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Service categories (Automotive, Residential…) and the individual services under them. Each gets its own page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: number;
  /**
   * e.g. "Car Lockout"
   */
  title: string;
  /**
   * A category lists its services; a service sits under a category.
   */
  kind: 'category' | 'service' | 'standalone';
  /**
   * For services only: the category this belongs to.
   */
  category?: (number | null) | Service;
  /**
   * One or two lines. Shown on the home page service card.
   */
  shortDescription: string;
  /**
   * Icon shown on cards and lists.
   */
  icon: 'car' | 'home' | 'building' | 'key' | 'smart' | 'shield' | 'lock';
  /**
   * Optional. Falls back to the site default hero image.
   */
  heroImage?: (number | null) | Media;
  /**
   * Opening paragraph on the service page.
   */
  intro: string;
  /**
   * The main write-up. Headings, lists and links all work.
   */
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Checklist shown on the page (used for Commercial, Emergency and Garage).
   */
  bullets?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Every city page shows the same service cards. Leave blank to keep this service off city pages.
   */
  cityCard?: {
    /**
     * Short label, e.g. "Rekey / Lock Change". Defaults to the page title.
     */
    title?: string | null;
    /**
     * One line. Write {city} where the city name should go.
     */
    text?: string | null;
  };
  /**
   * Shown in a highlighted box under the intro. Used on the Garage page to say this is lock service only, not garage door repair.
   */
  disclaimer?: string | null;
  /**
   * Optional call-button wording for this page, e.g. "LOCKED OUT? CALL NOW".
   */
  ctaLabel?: string | null;
  /**
   * Links shown at the bottom of the page.
   */
  related?: (number | Service)[] | null;
  /**
   * Questions shown on this service page.
   */
  faqs?: (number | Faq)[] | null;
  /**
   * Confirmed starting price only, e.g. "$95" or "From $45 / lock". Leave blank until pricing is confirmed — nothing is shown then.
   */
  startingPrice?: string | null;
  /**
   * Shown in the pricing table Notes column.
   */
  priceNote?: string | null;
  showInPricingTable?: boolean | null;
  /**
   * Optional. Leave blank to use the page title and intro text.
   */
  seo?: {
    /**
     * Best under 60 characters.
     */
    title?: string | null;
    /**
     * Best under 155 characters.
     */
    description?: string | null;
    /**
     * Shown when the page is shared on social media.
     */
    image?: (number | null) | Media;
    noindex?: boolean | null;
  };
  /**
   * The web address. Auto-filled from the title if left blank.
   */
  slug?: string | null;
  /**
   * Lower numbers appear first.
   */
  order?: number | null;
  /**
   * Show on the home page.
   */
  featured?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Photos used across the website.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * Answers reused across the site. Attach them to services from the service page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs".
 */
export interface Faq {
  id: number;
  question: string;
  answer: string;
  showOnHome?: boolean | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Cities and San Jose districts you serve. Each one gets a page. This is a service area, not a list of shops.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "locations".
 */
export interface Location {
  id: number;
  /**
   * e.g. "San Jose"
   */
  city: string;
  /**
   * e.g. "California"
   */
  state: string;
  /**
   * Two letters, e.g. "CA". Used in addresses.
   */
  stateAbbr: string;
  /**
   * Which part of the Bay Area this city belongs to. Groups it on the Bay Area page.
   */
  subregion: 'south-bay' | 'peninsula' | 'east-bay' | 'tri-valley';
  /**
   * Only for districts inside a city (e.g. North San Jose → San Jose). Nested under the parent in breadcrumbs and left out of the Bay Area page.
   */
  parent?: (number | null) | Location;
  /**
   * Shown as links at the bottom of the page.
   */
  nearby?: (number | Location)[] | null;
  /**
   * Small label above the page heading. Defaults to the region name.
   */
  badge?: string | null;
  /**
   * Only if there is a real, confirmed shop or dispatch hub here. Leave blank otherwise.
   */
  shopName?: string | null;
  /**
   * e.g. "Dispatch hub". Leave blank if there is no physical location.
   */
  shopSubtitle?: string | null;
  /**
   * City photo used on the location card and page header.
   */
  image?: (number | null) | Media;
  /**
   * Street address of a real location only
   */
  addressLine?: string | null;
  /**
   * ZIP code
   */
  postcode?: string | null;
  /**
   * Leave blank to use the main site phone number.
   */
  phone?: string | null;
  /**
   * Confirmed opening hours for a physical location here. Leave blank otherwise.
   */
  hours?: string | null;
  /**
   * Optional Google Maps link for the "Get directions" button.
   */
  mapUrl?: string | null;
  /**
   * Listed as pills on the page. Helps local search.
   */
  neighbourhoods?:
    | {
        name: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Opening paragraph on the city page.
   */
  intro?: string | null;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Service cards shown on this page, in order. Leave empty to show every service.
   */
  services?: (number | Service)[] | null;
  /**
   * Optional. Leave blank to use the page title and intro text.
   */
  seo?: {
    /**
     * Best under 60 characters.
     */
    title?: string | null;
    /**
     * Best under 155 characters.
     */
    description?: string | null;
    /**
     * Shown when the page is shared on social media.
     */
    image?: (number | null) | Media;
    noindex?: boolean | null;
  };
  /**
   * The web address. Auto-filled from the title if left blank.
   */
  slug?: string | null;
  /**
   * Lower numbers appear first.
   */
  order?: number | null;
  /**
   * Show in the home page and footer city lists.
   */
  featured?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Customer reviews. Featured ones scroll across the home page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews".
 */
export interface Review {
  id: number;
  /**
   * The review itself, without quote marks.
   */
  quote: string;
  /**
   * e.g. "Priya M."
   */
  author: string;
  /**
   * e.g. "San Jose, CA"
   */
  cityLabel?: string | null;
  /**
   * Stars, 1 to 5.
   */
  rating: number;
  source?: ('google' | 'yelp' | 'direct') | null;
  /**
   * Optional. Shows this review on that city page.
   */
  location?: (number | null) | Location;
  /**
   * Optional. Shows this review on that service page.
   */
  service?: (number | null) | Service;
  /**
   * Include in the scrolling home page strip.
   */
  featured?: boolean | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Standalone pages such as About, Privacy and Terms.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  /**
   * Shown under the page heading.
   */
  intro?: string | null;
  body: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  showCta?: boolean | null;
  /**
   * Optional. Leave blank to use the page title and intro text.
   */
  seo?: {
    /**
     * Best under 60 characters.
     */
    title?: string | null;
    /**
     * Best under 155 characters.
     */
    description?: string | null;
    /**
     * Shown when the page is shared on social media.
     */
    image?: (number | null) | Media;
    noindex?: boolean | null;
  };
  /**
   * The web address. Auto-filled from the title if left blank.
   */
  slug?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  /**
   * Shown in the top-right of the admin bar.
   */
  name: string;
  role: 'admin' | 'editor';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'enquiries';
        value: number | Enquiry;
      } | null)
    | ({
        relationTo: 'services';
        value: number | Service;
      } | null)
    | ({
        relationTo: 'locations';
        value: number | Location;
      } | null)
    | ({
        relationTo: 'reviews';
        value: number | Review;
      } | null)
    | ({
        relationTo: 'faqs';
        value: number | Faq;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "enquiries_select".
 */
export interface EnquiriesSelect<T extends boolean = true> {
  type?: T;
  status?: T;
  name?: T;
  phone?: T;
  email?: T;
  serviceLabel?: T;
  cityLabel?: T;
  when?: T;
  message?: T;
  sourcePage?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  title?: T;
  kind?: T;
  category?: T;
  shortDescription?: T;
  icon?: T;
  heroImage?: T;
  intro?: T;
  body?: T;
  bullets?:
    | T
    | {
        text?: T;
        id?: T;
      };
  cityCard?:
    | T
    | {
        title?: T;
        text?: T;
      };
  disclaimer?: T;
  ctaLabel?: T;
  related?: T;
  faqs?: T;
  startingPrice?: T;
  priceNote?: T;
  showInPricingTable?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        noindex?: T;
      };
  slug?: T;
  order?: T;
  featured?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "locations_select".
 */
export interface LocationsSelect<T extends boolean = true> {
  city?: T;
  state?: T;
  stateAbbr?: T;
  subregion?: T;
  parent?: T;
  nearby?: T;
  badge?: T;
  shopName?: T;
  shopSubtitle?: T;
  image?: T;
  addressLine?: T;
  postcode?: T;
  phone?: T;
  hours?: T;
  mapUrl?: T;
  neighbourhoods?:
    | T
    | {
        name?: T;
        id?: T;
      };
  intro?: T;
  body?: T;
  services?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        noindex?: T;
      };
  slug?: T;
  order?: T;
  featured?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews_select".
 */
export interface ReviewsSelect<T extends boolean = true> {
  quote?: T;
  author?: T;
  cityLabel?: T;
  rating?: T;
  source?: T;
  location?: T;
  service?: T;
  featured?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs_select".
 */
export interface FaqsSelect<T extends boolean = true> {
  question?: T;
  answer?: T;
  showOnHome?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  intro?: T;
  body?: T;
  showCta?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        noindex?: T;
      };
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Every word on the home page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page".
 */
export interface HomePage {
  id: number;
  eyebrow?: string | null;
  /**
   * Shown in dark navy.
   */
  headingLine1: string;
  /**
   * Shown in orange, below the first line.
   */
  headingLine2: string;
  lede: string;
  /**
   * The van and technician photo.
   */
  heroImage?: (number | null) | Media;
  /**
   * The phone number is added automatically.
   */
  primaryCtaLabel?: string | null;
  secondaryCtaLabel?: string | null;
  trustItems?:
    | {
        icon: 'clock' | 'shield' | 'people' | 'star';
        /**
         * Bold line, e.g. "Licensed & Insured"
         */
        value: string;
        /**
         * Grey line, e.g. "CA BSIS"
         */
        label: string;
        id?: string | null;
      }[]
    | null;
  categories?:
    | {
        icon: 'car' | 'home' | 'building' | 'key' | 'shield';
        label: string;
        id?: string | null;
      }[]
    | null;
  locationsEyebrow?: string | null;
  locationsHeading?: string | null;
  servicesEyebrow?: string | null;
  servicesHeading?: string | null;
  reviewsHeading?: string | null;
  reviewsSubtitle?: string | null;
  shopsEyebrow?: string | null;
  shopsHeading?: string | null;
  shopsSubtitle?: string | null;
  aboutEyebrow?: string | null;
  aboutHeading?: string | null;
  aboutLead?: string | null;
  aboutFeatures?:
    | {
        icon: 'shield' | 'key' | 'people' | 'clock' | 'star';
        title: string;
        text: string;
        id?: string | null;
      }[]
    | null;
  aboutCtaLabel?: string | null;
  faqBarText?: string | null;
  pricingEyebrow?: string | null;
  pricingHeading?: string | null;
  pricingSubtitle?: string | null;
  faqEyebrow?: string | null;
  faqHeading?: string | null;
  /**
   * Optional. Leave blank to use the page title and intro text.
   */
  seo?: {
    /**
     * Best under 60 characters.
     */
    title?: string | null;
    /**
     * Best under 155 characters.
     */
    description?: string | null;
    /**
     * Shown when the page is shared on social media.
     */
    image?: (number | null) | Media;
    noindex?: boolean | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Every heading and intro that is not part of a service or city page itself — index pages, the repeated section labels on city and service pages, and the standard city FAQs.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "page-copy".
 */
export interface PageCopy {
  id: number;
  services: {
    /**
     * Small orange line above the heading.
     */
    eyebrow?: string | null;
    title: string;
    /**
     * Also used as the page description in search results.
     */
    intro?: string | null;
  };
  locations: {
    /**
     * Small orange line above the heading.
     */
    eyebrow?: string | null;
    title: string;
    /**
     * Also used as the page description in search results.
     */
    intro?: string | null;
  };
  reviews: {
    /**
     * Small orange line above the heading.
     */
    eyebrow?: string | null;
    title: string;
    /**
     * Also used as the page description in search results.
     */
    intro?: string | null;
  };
  faq: {
    /**
     * Small orange line above the heading.
     */
    eyebrow?: string | null;
    title: string;
    /**
     * Also used as the page description in search results.
     */
    intro?: string | null;
  };
  pricing: {
    /**
     * Small orange line above the heading.
     */
    eyebrow?: string | null;
    title: string;
    /**
     * Also used as the page description in search results.
     */
    intro?: string | null;
  };
  pricingNote?: string | null;
  book: {
    /**
     * Small orange line above the heading.
     */
    eyebrow?: string | null;
    title: string;
    /**
     * Also used as the page description in search results.
     */
    intro?: string | null;
  };
  bookSideTitle?: string | null;
  bookSideText?: string | null;
  contact: {
    /**
     * Small orange line above the heading.
     */
    eyebrow?: string | null;
    title: string;
    /**
     * Also used as the page description in search results.
     */
    intro?: string | null;
  };
  contactFormHeading?: string | null;
  contactShopsHeading?: string | null;
  thankYou: {
    /**
     * Small orange line above the heading.
     */
    eyebrow?: string | null;
    title: string;
    /**
     * Also used as the page description in search results.
     */
    intro?: string | null;
  };
  thankYouUrgentTitle?: string | null;
  thankYouUrgentText?: string | null;
  /**
   * Use {arrival} to insert the average arrival time from Site settings.
   */
  thankYouSteps?:
    | {
        title: string;
        text: string;
        id?: string | null;
      }[]
    | null;
  aboutStandardsEyebrow?: string | null;
  aboutStandardsHeading?: string | null;
  aboutStandardsIntro?: string | null;
  aboutPillars?:
    | {
        icon: 'shield' | 'key' | 'people' | 'clock' | 'star';
        title: string;
        text: string;
        id?: string | null;
      }[]
    | null;
  aboutAreasHeading?: string | null;
  aboutAreasText?: string | null;
  aboutHubsHeading?: string | null;
  cityNeighborhoodsEyebrow?: string | null;
  cityNeighborhoodsHeading?: string | null;
  cityServicesEyebrow?: string | null;
  cityServicesHeading?: string | null;
  cityCtaHeading?: string | null;
  cityCtaSubtitle?: string | null;
  cityFaqEyebrow?: string | null;
  cityFaqHeading?: string | null;
  /**
   * Shown on all city pages. Use {city} for the city name and {arrival} for the average arrival time — a question using {arrival} is hidden until that figure is filled in under Site settings.
   */
  cityFaqs?:
    | {
        question: string;
        answer: string;
        id?: string | null;
      }[]
    | null;
  cityNearbyEyebrow?: string | null;
  cityNearbyHeading?: string | null;
  serviceIncludedHeading?: string | null;
  serviceCtaSubtitle?: string | null;
  serviceAreasEyebrow?: string | null;
  serviceAreasHeading?: string | null;
  serviceRelatedEyebrow?: string | null;
  serviceRelatedHeading?: string | null;
  hubRegionsEyebrow?: string | null;
  hubRegionsHeading?: string | null;
  hubCtaHeading?: string | null;
  pricingEmptyHeading?: string | null;
  pricingEmptyText?: string | null;
  reviewsEmptyHeading?: string | null;
  reviewsEmptyText?: string | null;
  /**
   * The dark banner at the foot of most pages. Service and city pages override it with their own.
   */
  ctaHeading?: string | null;
  ctaSubtitle?: string | null;
  /**
   * Shown under "[Service] near you" on every service page.
   */
  serviceCitySubtitle?: string | null;
  callCardTitle?: string | null;
  callCardSubtitle?: string | null;
  callCardNote?: string | null;
  notFound: {
    /**
     * Small orange line above the heading.
     */
    eyebrow?: string | null;
    title: string;
    /**
     * Also used as the page description in search results.
     */
    intro?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Wording for the "[service] in [city]" pages. Use {service}, {city}, {state}, {phone}, {arrival} and {price} — they are swapped for the real values on each page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "combo-template".
 */
export interface ComboTemplate {
  id: number;
  /**
   * Turning this off removes them from the site and the sitemap.
   */
  enabled?: boolean | null;
  eyebrow?: string | null;
  heading: string;
  intro: string;
  bodyHeading?: string | null;
  /**
   * A paragraph or two. Placeholders work here too.
   */
  body?: string | null;
  ctaHeading?: string | null;
  seoTitle?: string | null;
  seoDescription?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Phone number, licence, hours and trust badges — used across every page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  companyName: string;
  tagline?: string | null;
  /**
   * As displayed, e.g. "(408) 000-0000". REQUIRED before launch.
   */
  phone?: string | null;
  /**
   * As dialled, digits only with country code, e.g. "+14080000000".
   */
  phoneHref?: string | null;
  email?: string | null;
  /**
   * California BSIS locksmith licence, e.g. "CA BSIS Lic. #LCO 1234". REQUIRED by law on all advertising before launch.
   */
  licenseNumber?: string | null;
  /**
   * Confirmed operating hours, e.g. "Mon–Sun 7am–10pm". Leave blank until confirmed — never claim 24/7 unless it is true.
   */
  hours?: string | null;
  /**
   * One line shown in the footer and header strip.
   */
  serviceAreaLine?: string | null;
  /**
   * Confirmed physical addresses only. This is a mobile service area business — cities are served from these hubs, they do not each have a shop.
   */
  dispatchHubs?:
    | {
        /**
         * e.g. "Santa Clara dispatch hub"
         */
        name: string;
        addressLine: string;
        city: string;
        stateAbbr: string;
        /**
         * ZIP
         */
        postcode?: string | null;
        /**
         * Optional Google Maps link.
         */
        mapUrl?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Verified rating, e.g. "4.8/5"
   */
  rating?: string | null;
  /**
   * Verified review count
   */
  reviewCount?: number | null;
  /**
   * Only a tracked, verified average, e.g. "25 min". Leave blank otherwise.
   */
  averageArrival?: string | null;
  /**
   * The handwritten line on the hero image.
   */
  scriptLine?: string | null;
  logo?: (number | null) | Media;
  /**
   * Used on any page without its own image.
   */
  defaultHeroImage?: (number | null) | Media;
  /**
   * Shown when a page is shared on social media.
   */
  defaultSeoImage?: (number | null) | Media;
  /**
   * Looks like "G-XXXXXXXXXX". From Google Analytics → Admin → Data streams.
   */
  googleAnalyticsId?: string | null;
  /**
   * The content value from the HTML tag Search Console gives you, e.g. "abc123…". Only the code, not the whole tag.
   */
  googleSiteVerification?: string | null;
  social?:
    | {
        platform: 'google' | 'facebook' | 'instagram' | 'yelp' | 'x';
        url: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * The top menu and the footer link columns.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation".
 */
export interface Navigation {
  id: number;
  /**
   * Keep this to about six items so it fits on one line.
   */
  header?:
    | {
        label: string;
        /**
         * e.g. "/services" or "/locations/san-jose"
         */
        href: string;
        id?: string | null;
      }[]
    | null;
  footerColumns?:
    | {
        heading: string;
        links?:
          | {
              label: string;
              href: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Small print above the copyright line.
   */
  footerNote?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page_select".
 */
export interface HomePageSelect<T extends boolean = true> {
  eyebrow?: T;
  headingLine1?: T;
  headingLine2?: T;
  lede?: T;
  heroImage?: T;
  primaryCtaLabel?: T;
  secondaryCtaLabel?: T;
  trustItems?:
    | T
    | {
        icon?: T;
        value?: T;
        label?: T;
        id?: T;
      };
  categories?:
    | T
    | {
        icon?: T;
        label?: T;
        id?: T;
      };
  locationsEyebrow?: T;
  locationsHeading?: T;
  servicesEyebrow?: T;
  servicesHeading?: T;
  reviewsHeading?: T;
  reviewsSubtitle?: T;
  shopsEyebrow?: T;
  shopsHeading?: T;
  shopsSubtitle?: T;
  aboutEyebrow?: T;
  aboutHeading?: T;
  aboutLead?: T;
  aboutFeatures?:
    | T
    | {
        icon?: T;
        title?: T;
        text?: T;
        id?: T;
      };
  aboutCtaLabel?: T;
  faqBarText?: T;
  pricingEyebrow?: T;
  pricingHeading?: T;
  pricingSubtitle?: T;
  faqEyebrow?: T;
  faqHeading?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        noindex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "page-copy_select".
 */
export interface PageCopySelect<T extends boolean = true> {
  services?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        intro?: T;
      };
  locations?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        intro?: T;
      };
  reviews?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        intro?: T;
      };
  faq?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        intro?: T;
      };
  pricing?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        intro?: T;
      };
  pricingNote?: T;
  book?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        intro?: T;
      };
  bookSideTitle?: T;
  bookSideText?: T;
  contact?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        intro?: T;
      };
  contactFormHeading?: T;
  contactShopsHeading?: T;
  thankYou?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        intro?: T;
      };
  thankYouUrgentTitle?: T;
  thankYouUrgentText?: T;
  thankYouSteps?:
    | T
    | {
        title?: T;
        text?: T;
        id?: T;
      };
  aboutStandardsEyebrow?: T;
  aboutStandardsHeading?: T;
  aboutStandardsIntro?: T;
  aboutPillars?:
    | T
    | {
        icon?: T;
        title?: T;
        text?: T;
        id?: T;
      };
  aboutAreasHeading?: T;
  aboutAreasText?: T;
  aboutHubsHeading?: T;
  cityNeighborhoodsEyebrow?: T;
  cityNeighborhoodsHeading?: T;
  cityServicesEyebrow?: T;
  cityServicesHeading?: T;
  cityCtaHeading?: T;
  cityCtaSubtitle?: T;
  cityFaqEyebrow?: T;
  cityFaqHeading?: T;
  cityFaqs?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  cityNearbyEyebrow?: T;
  cityNearbyHeading?: T;
  serviceIncludedHeading?: T;
  serviceCtaSubtitle?: T;
  serviceAreasEyebrow?: T;
  serviceAreasHeading?: T;
  serviceRelatedEyebrow?: T;
  serviceRelatedHeading?: T;
  hubRegionsEyebrow?: T;
  hubRegionsHeading?: T;
  hubCtaHeading?: T;
  pricingEmptyHeading?: T;
  pricingEmptyText?: T;
  reviewsEmptyHeading?: T;
  reviewsEmptyText?: T;
  ctaHeading?: T;
  ctaSubtitle?: T;
  serviceCitySubtitle?: T;
  callCardTitle?: T;
  callCardSubtitle?: T;
  callCardNote?: T;
  notFound?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        intro?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "combo-template_select".
 */
export interface ComboTemplateSelect<T extends boolean = true> {
  enabled?: T;
  eyebrow?: T;
  heading?: T;
  intro?: T;
  bodyHeading?: T;
  body?: T;
  ctaHeading?: T;
  seoTitle?: T;
  seoDescription?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  companyName?: T;
  tagline?: T;
  phone?: T;
  phoneHref?: T;
  email?: T;
  licenseNumber?: T;
  hours?: T;
  serviceAreaLine?: T;
  dispatchHubs?:
    | T
    | {
        name?: T;
        addressLine?: T;
        city?: T;
        stateAbbr?: T;
        postcode?: T;
        mapUrl?: T;
        id?: T;
      };
  rating?: T;
  reviewCount?: T;
  averageArrival?: T;
  scriptLine?: T;
  logo?: T;
  defaultHeroImage?: T;
  defaultSeoImage?: T;
  googleAnalyticsId?: T;
  googleSiteVerification?: T;
  social?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation_select".
 */
export interface NavigationSelect<T extends boolean = true> {
  header?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  footerColumns?:
    | T
    | {
        heading?: T;
        links?:
          | T
          | {
              label?: T;
              href?: T;
              id?: T;
            };
        id?: T;
      };
  footerNote?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}