/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    enquiries: Enquiry;
    services: Service;
    locations: Location;
    reviews: Review;
    faqs: Faq;
    pages: Page;
    media: Media;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    enquiries: EnquiriesSelect<false> | EnquiriesSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    locations: LocationsSelect<false> | LocationsSelect<true>;
    reviews: ReviewsSelect<false> | ReviewsSelect<true>;
    faqs: FaqsSelect<false> | FaqsSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'home-page': HomePage;
    'combo-template': ComboTemplate;
    'site-settings': SiteSetting;
    navigation: Navigation;
  };
  globalsSelect: {
    'home-page': HomePageSelect<false> | HomePageSelect<true>;
    'combo-template': ComboTemplateSelect<false> | ComboTemplateSelect<true>;
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    navigation: NavigationSelect<false> | NavigationSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Service orders and quote requests from the website.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "enquiries".
 */
export interface Enquiry {
  id: number;
  type: 'order' | 'quote' | 'contact';
  status: 'new' | 'contacted' | 'booked' | 'closed';
  name: string;
  phone: string;
  email?: string | null;
  serviceLabel?: string | null;
  cityLabel?: string | null;
  /**
   * When they need it.
   */
  when?: string | null;
  message?: string | null;
  /**
   * The page the form was submitted from.
   */
  sourcePage?: string | null;
  /**
   * Internal notes. Not shown to the customer.
   */
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Each service gets its own page, and one page per city it is offered in.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: number;
  /**
   * e.g. "Car Lockout"
   */
  title: string;
  /**
   * One or two lines. Shown on the home page service card.
   */
  shortDescription: string;
  /**
   * Icon shown on cards and lists.
   */
  icon: 'car' | 'home' | 'building' | 'key' | 'smart' | 'shield' | 'lock';
  /**
   * Optional. Falls back to the site default hero image.
   */
  heroImage?: (number | null) | Media;
  /**
   * Opening paragraph on the service page.
   */
  intro: string;
  /**
   * The main write-up. Headings, lists and links all work.
   */
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Short checklist shown beside the write-up.
   */
  bullets?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Questions shown on this service page.
   */
  faqs?: (number | Faq)[] | null;
  /**
   * e.g. "$95" or "From $45 / lock" or "Custom quote"
   */
  startingPrice: string;
  /**
   * Shown in the pricing table Notes column.
   */
  priceNote?: string | null;
  showInPricingTable?: boolean | null;
  /**
   * Optional. Leave blank to use the page title and intro text.
   */
  seo?: {
    /**
     * Best under 60 characters.
     */
    title?: string | null;
    /**
     * Best under 155 characters.
     */
    description?: string | null;
    /**
     * Shown when the page is shared on social media.
     */
    image?: (number | null) | Media;
    noindex?: boolean | null;
  };
  /**
   * The web address. Auto-filled from the title if left blank.
   */
  slug?: string | null;
  /**
   * Lower numbers appear first.
   */
  order?: number | null;
  /**
   * Show on the home page.
   */
  featured?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Photos used across the website.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * Answers reused across the site. Attach them to services from the service page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs".
 */
export interface Faq {
  id: number;
  question: string;
  answer: string;
  showOnHome?: boolean | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Cities you serve. Each one gets a page, plus a page for every service.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "locations".
 */
export interface Location {
  id: number;
  /**
   * e.g. "San Jose"
   */
  city: string;
  /**
   * e.g. "California"
   */
  state: string;
  /**
   * Two letters, e.g. "CA". Used in addresses.
   */
  stateAbbr: string;
  /**
   * Label on the shop card, e.g. "California HQ".
   */
  badge?: string | null;
  /**
   * e.g. "888 Lock & Key — San Jose"
   */
  shopName?: string | null;
  /**
   * e.g. "Main shop & dispatch center"
   */
  shopSubtitle?: string | null;
  /**
   * City photo used on the location card and page header.
   */
  image?: (number | null) | Media;
  /**
   * Street address
   */
  addressLine?: string | null;
  /**
   * ZIP code
   */
  postcode?: string | null;
  /**
   * Leave blank to use the main site phone number.
   */
  phone?: string | null;
  /**
   * e.g. "Open 24 hours · walk-ins 8am–7pm"
   */
  hours?: string | null;
  /**
   * Optional Google Maps link for the "Get directions" button.
   */
  mapUrl?: string | null;
  /**
   * Listed on the location page. Helps local search.
   */
  neighbourhoods?:
    | {
        name: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Opening paragraph on the city page.
   */
  intro?: string | null;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Services offered here. Leave empty to offer every service.
   */
  services?: (number | Service)[] | null;
  /**
   * Optional. Leave blank to use the page title and intro text.
   */
  seo?: {
    /**
     * Best under 60 characters.
     */
    title?: string | null;
    /**
     * Best under 155 characters.
     */
    description?: string | null;
    /**
     * Shown when the page is shared on social media.
     */
    image?: (number | null) | Media;
    noindex?: boolean | null;
  };
  /**
   * The web address. Auto-filled from the title if left blank.
   */
  slug?: string | null;
  /**
   * Lower numbers appear first.
   */
  order?: number | null;
  /**
   * Show in the home page city strip.
   */
  featured?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Customer reviews. Featured ones scroll across the home page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews".
 */
export interface Review {
  id: number;
  /**
   * The review itself, without quote marks.
   */
  quote: string;
  /**
   * e.g. "Priya M."
   */
  author: string;
  /**
   * e.g. "San Jose, CA"
   */
  cityLabel?: string | null;
  /**
   * Stars, 1 to 5.
   */
  rating: number;
  source?: ('google' | 'yelp' | 'direct') | null;
  /**
   * Optional. Shows this review on that city page.
   */
  location?: (number | null) | Location;
  /**
   * Optional. Shows this review on that service page.
   */
  service?: (number | null) | Service;
  /**
   * Include in the scrolling home page strip.
   */
  featured?: boolean | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Standalone pages such as About, Privacy and Terms.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  /**
   * Shown under the page heading.
   */
  intro?: string | null;
  body: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  showCta?: boolean | null;
  /**
   * Optional. Leave blank to use the page title and intro text.
   */
  seo?: {
    /**
     * Best under 60 characters.
     */
    title?: string | null;
    /**
     * Best under 155 characters.
     */
    description?: string | null;
    /**
     * Shown when the page is shared on social media.
     */
    image?: (number | null) | Media;
    noindex?: boolean | null;
  };
  /**
   * The web address. Auto-filled from the title if left blank.
   */
  slug?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  /**
   * Shown in the top-right of the admin bar.
   */
  name: string;
  role: 'admin' | 'editor';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'enquiries';
        value: number | Enquiry;
      } | null)
    | ({
        relationTo: 'services';
        value: number | Service;
      } | null)
    | ({
        relationTo: 'locations';
        value: number | Location;
      } | null)
    | ({
        relationTo: 'reviews';
        value: number | Review;
      } | null)
    | ({
        relationTo: 'faqs';
        value: number | Faq;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "enquiries_select".
 */
export interface EnquiriesSelect<T extends boolean = true> {
  type?: T;
  status?: T;
  name?: T;
  phone?: T;
  email?: T;
  serviceLabel?: T;
  cityLabel?: T;
  when?: T;
  message?: T;
  sourcePage?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  title?: T;
  shortDescription?: T;
  icon?: T;
  heroImage?: T;
  intro?: T;
  body?: T;
  bullets?:
    | T
    | {
        text?: T;
        id?: T;
      };
  faqs?: T;
  startingPrice?: T;
  priceNote?: T;
  showInPricingTable?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        noindex?: T;
      };
  slug?: T;
  order?: T;
  featured?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "locations_select".
 */
export interface LocationsSelect<T extends boolean = true> {
  city?: T;
  state?: T;
  stateAbbr?: T;
  badge?: T;
  shopName?: T;
  shopSubtitle?: T;
  image?: T;
  addressLine?: T;
  postcode?: T;
  phone?: T;
  hours?: T;
  mapUrl?: T;
  neighbourhoods?:
    | T
    | {
        name?: T;
        id?: T;
      };
  intro?: T;
  body?: T;
  services?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        noindex?: T;
      };
  slug?: T;
  order?: T;
  featured?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews_select".
 */
export interface ReviewsSelect<T extends boolean = true> {
  quote?: T;
  author?: T;
  cityLabel?: T;
  rating?: T;
  source?: T;
  location?: T;
  service?: T;
  featured?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs_select".
 */
export interface FaqsSelect<T extends boolean = true> {
  question?: T;
  answer?: T;
  showOnHome?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  intro?: T;
  body?: T;
  showCta?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        noindex?: T;
      };
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Every word on the home page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page".
 */
export interface HomePage {
  id: number;
  eyebrow?: string | null;
  /**
   * Shown in dark navy.
   */
  headingLine1: string;
  /**
   * Shown in orange, below the first line.
   */
  headingLine2: string;
  lede: string;
  /**
   * The van and technician photo.
   */
  heroImage?: (number | null) | Media;
  /**
   * The phone number is added automatically.
   */
  primaryCtaLabel?: string | null;
  secondaryCtaLabel?: string | null;
  trustItems?:
    | {
        icon: 'clock' | 'shield' | 'people' | 'star';
        /**
         * Bold line, e.g. "24/7"
         */
        value: string;
        /**
         * Grey line, e.g. "Emergency Service"
         */
        label: string;
        id?: string | null;
      }[]
    | null;
  categories?:
    | {
        icon: 'car' | 'home' | 'building' | 'key' | 'shield';
        label: string;
        id?: string | null;
      }[]
    | null;
  locationsEyebrow?: string | null;
  locationsHeading?: string | null;
  servicesEyebrow?: string | null;
  servicesHeading?: string | null;
  reviewsHeading?: string | null;
  reviewsSubtitle?: string | null;
  shopsEyebrow?: string | null;
  shopsHeading?: string | null;
  shopsSubtitle?: string | null;
  pricingEyebrow?: string | null;
  pricingHeading?: string | null;
  pricingSubtitle?: string | null;
  faqEyebrow?: string | null;
  faqHeading?: string | null;
  /**
   * Optional. Leave blank to use the page title and intro text.
   */
  seo?: {
    /**
     * Best under 60 characters.
     */
    title?: string | null;
    /**
     * Best under 155 characters.
     */
    description?: string | null;
    /**
     * Shown when the page is shared on social media.
     */
    image?: (number | null) | Media;
    noindex?: boolean | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Wording for the "[service] in [city]" pages. Use {service}, {city}, {state}, {phone}, {arrival} and {price} — they are swapped for the real values on each page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "combo-template".
 */
export interface ComboTemplate {
  id: number;
  /**
   * Turning this off removes them from the site and the sitemap.
   */
  enabled?: boolean | null;
  eyebrow?: string | null;
  heading: string;
  intro: string;
  bodyHeading?: string | null;
  /**
   * A paragraph or two. Placeholders work here too.
   */
  body?: string | null;
  ctaHeading?: string | null;
  seoTitle?: string | null;
  seoDescription?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Phone number, licence, hours and trust badges — used across every page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  companyName: string;
  tagline?: string | null;
  /**
   * Displayed, e.g. "(408) 555-0888"
   */
  phone: string;
  /**
   * Dialled, e.g. "+14085550888"
   */
  phoneHref: string;
  email?: string | null;
  /**
   * e.g. "BSIS #LCO-000000"
   */
  licenseNumber?: string | null;
  hours?: string | null;
  /**
   * e.g. "Across California, Arizona & New York"
   */
  serviceAreaLine?: string | null;
  rating?: string | null;
  reviewCount?: number | null;
  /**
   * e.g. "24 MIN"
   */
  averageArrival?: string | null;
  /**
   * The handwritten line on the hero image.
   */
  scriptLine?: string | null;
  logo?: (number | null) | Media;
  /**
   * Used on any page without its own image.
   */
  defaultHeroImage?: (number | null) | Media;
  /**
   * Shown when a page is shared on social media.
   */
  defaultSeoImage?: (number | null) | Media;
  social?:
    | {
        platform: 'google' | 'facebook' | 'instagram' | 'yelp' | 'x';
        url: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * The top menu and the footer link columns.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation".
 */
export interface Navigation {
  id: number;
  /**
   * Keep this to about six items so it fits on one line.
   */
  header?:
    | {
        label: string;
        /**
         * e.g. "/services" or "/locations/san-jose"
         */
        href: string;
        id?: string | null;
      }[]
    | null;
  footerColumns?:
    | {
        heading: string;
        links?:
          | {
              label: string;
              href: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Small print above the copyright line.
   */
  footerNote?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page_select".
 */
export interface HomePageSelect<T extends boolean = true> {
  eyebrow?: T;
  headingLine1?: T;
  headingLine2?: T;
  lede?: T;
  heroImage?: T;
  primaryCtaLabel?: T;
  secondaryCtaLabel?: T;
  trustItems?:
    | T
    | {
        icon?: T;
        value?: T;
        label?: T;
        id?: T;
      };
  categories?:
    | T
    | {
        icon?: T;
        label?: T;
        id?: T;
      };
  locationsEyebrow?: T;
  locationsHeading?: T;
  servicesEyebrow?: T;
  servicesHeading?: T;
  reviewsHeading?: T;
  reviewsSubtitle?: T;
  shopsEyebrow?: T;
  shopsHeading?: T;
  shopsSubtitle?: T;
  pricingEyebrow?: T;
  pricingHeading?: T;
  pricingSubtitle?: T;
  faqEyebrow?: T;
  faqHeading?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        noindex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "combo-template_select".
 */
export interface ComboTemplateSelect<T extends boolean = true> {
  enabled?: T;
  eyebrow?: T;
  heading?: T;
  intro?: T;
  bodyHeading?: T;
  body?: T;
  ctaHeading?: T;
  seoTitle?: T;
  seoDescription?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  companyName?: T;
  tagline?: T;
  phone?: T;
  phoneHref?: T;
  email?: T;
  licenseNumber?: T;
  hours?: T;
  serviceAreaLine?: T;
  rating?: T;
  reviewCount?: T;
  averageArrival?: T;
  scriptLine?: T;
  logo?: T;
  defaultHeroImage?: T;
  defaultSeoImage?: T;
  social?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation_select".
 */
export interface NavigationSelect<T extends boolean = true> {
  header?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  footerColumns?:
    | T
    | {
        heading?: T;
        links?:
          | T
          | {
              label?: T;
              href?: T;
              id?: T;
            };
        id?: T;
      };
  footerNote?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}